#! /bin/bash

set -e

USAGE="
Usage:
 poliopoly -i <input_dir> -o <output_dir> -t <S1|S2|S3> -b <primer_bed> -n <resume_name>

Options:
 -i <input_dir>     input directory which includes paired FASTQ files
 -o <output_dir>    output directory
 -t <S1|S2|S3>      reference polio serotype
 -b <primer_bed>    location of BED file of primers
 -n <resume_name>   resume of NextFlow, see https://bit.ly/3xpKmEK

Optional environment variables:
 IVAR_VARIANTS_MIN_FREQ    minimum frequency of \`ivar variants\` (default: 0.75)
 IVAR_VARIANTS_MIN_QUAL    minimum quality of \`ivar variants\` (default: 20)
 IVAR_VARIANTS_MIN_COV     minimum coverage of \`ivar variants\` (default: 10)
 IVAR_CONSENSUS_MIN_FREQ   minimum frequency of \`ivar consensus\` (default: 0.5)
 IVAR_CONSENSUS_MIN_QUAL   minimum quality of \`ivar consensus\` (default: 20)
 IVAR_CONSENSUS_MIN_COV    minimum coverage of \`ivar consensus\` (default: 50)
"

SKIP_REMOTE_DOCKER=0
IVAR_VARIANTS_MIN_FREQ=${IVAR_VARIANTS_MIN_FREQ:-0.75}
IVAR_VARIANTS_MIN_QUAL=${IVAR_VARIANTS_MIN_QUAL:-20}
IVAR_VARIANTS_MIN_COV=${IVAR_VARIANTS_MIN_COV:-10}
IVAR_CONSENSUS_MIN_FREQ=${IVAR_CONSENSUS_MIN_FREQ:-0.5}
IVAR_CONSENSUS_MIN_QUAL=${IVAR_CONSENSUS_MIN_QUAL:-20}
IVAR_CONSENSUS_MIN_COV=${IVAR_CONSENSUS_MIN_COV:-50}

while getopts ':i:o:t:b:n:s' OPT; do
  case "$OPT" in
    i) INPUT_DIR="$OPTARG" ;;
    o) OUTPUT_DIR="$OPTARG" ;;
    t) SEROTYPE="$OPTARG";;
    b) PRIMER_BED="$OPTARG" ;;
    n) RESUME_NAME="$OPTARG" ;;
    s) SKIP_REMOTE_DOCKER=1 ;;
    \?)
      echo $USAGE >&2
      exit 0
      ;;
    :) echo "missing option argument for -$OPTARG\n$USAGE" >&2; exit 1;;
    *) echo "unrecongnized option: -$OPTARG\n$USAGE" >&2; exit 1;;
  esac
done

if [ -z "$INPUT_DIR" ]; then
  echo "missing required option -i <input_dir>" >&2
  echo "$USAGE" >&2
  exit 1
fi

if [ ! -d "$INPUT_DIR" ]; then
  echo "-i $INPUT_DIR is not a directory or does not exist" >&2
  echo "$USAGE" >&2
  exit 1
fi

if [ -z "$OUTPUT_DIR" ]; then
  echo "missing required option -o <output_dir>" >&2
  echo "$USAGE" >&2
  exit 1
fi
mkdir -p $OUTPUT_DIR

if [ -z "$SEROTYPE" ]; then
  echo "missing required option -t <serotype>" >&2
  echo -e "$USAGE" >&2
  exit 1
fi

if [ -z "$PRIMER_BED" ]; then
  echo "missing required option -b <primer_bed>" >&2
  echo -e "$USAGE" >&2
  exit 1
fi

if [ -z "$RESUME_NAME" ]; then
  echo "missing required option -n <resume_name>" >&2
  echo -e "$USAGE" >&2
  exit 1
fi

case "$SEROTYPE" in
  1 | S1 )
    ;;
  2 | S2 )
    ;;
  3 | S3 )
    ;;
  * )
    echo "unrecongnized -t ${SEROTYPE}" >&2
    exit 1
    ;;
esac
